### ISSUE TITLE
Multiple Selected days in months, 1 per week

### ISSUE THREAD

**Issue by MikaelX** [kylestetz/CLNDR#193] opened 2015-07-09 07:01 UTC
With version 1.2.14 I've noticed that I can select one day per week instead of one day per month (which gets the selected class), can anyone confirm?

This gives that I can have 5 selected days of the month but I only want one :)

**Comment by mikegioia** [comment] 2015-07-09 13:58
@MikaelX I just ran through the tests and can't reproduce this. Is there a way you can replicate this in `example/test.html`?

**Comment by imensha** [comment] 2015-09-08 20:27
My guess is this is due to the `trackSelectedDate` option. It uses `siblings()` to remove the `selected` class, which means if all `day` elements are not siblings (for example, if the template nests days inside individual week elements), it is possible for multiple days to appear selected at the same time.

**Comment by melanke** [comment] 2015-10-24 11:31
A quickfix:
```javascript
$('#calendario').clndr({
    clickEvents: {
        click: function(target) {
            $("#calendario .selected").removeClass("selected");
            $(".calendar-day-"+target.date.format("YYYY-MM-DD")).addClass("selected");
        }
    }
});
```

**Comment by mikegioia** [comment] 2016-04-05 15:26
I'm going to close this one out, it seems you resolved it through the API methods.

**Closed by mikegioia** 2016-04-05 15:26 UTC
Labels: need info

**Comment by andie-chernysh** [comment] 2016-06-15 11:32
Facing the same issue. It's great there is a workaround using the API methods, but that's definitely not a fix, and the bug remains.

**Comment by melanke** [comment] 2016-09-10 03:58
I think I made a Kludge, I will not say the problem was solved
