### ISSUE TITLE
lengthOfTime weekOffset bug

### ISSUE THREAD

**Issue by rexxnar** [kylestetz/CLNDR#287] opened 2016-11-04 16:03 UTC
#### Context
I was setting up a calendar starting of for example at friday, and start day is a friday so you expect the calendar to start at friday top, and date friday.

#### Expected Behavior
![screen shot 2016-11-04 at 16 59 20](https://cloud.githubusercontent.com/assets/10832606/20012560/145055ce-a2b0-11e6-924f-ed59c62764df.png)

#### Actual Behavior
![screen shot 2016-11-04 at 17 00 03](https://cloud.githubusercontent.com/assets/10832606/20012604/3333329a-a2b0-11e6-9730-b2137f55cf91.png)

#### Possible Fix
In the file clndr.js on line 216 there is this line: this.intervalStart = moment().weekday(0).startOf('day');
It sets the weekday on 0, you could check for user settings or do it like this:
this.intervalStart = moment().weekday(this.options.weekOffset).startOf('day');
best if of course check if its set, then put it in

#### Steps to Reproduce
Set up a calendar with lengthOfTime days 28, interval 28.
start date 2016-11-04 (friday)
Week offset friday (5)

**Comment by mikegioia** [comment] 2016-12-01 19:27
This is interesting and it's a good find. I think I know what the problem is but I might not be able to look at it until the weekend. Sorry for the delay here.

**Comment by mikegioia** [comment] 2017-10-11 00:17
I finally got a PR together, with tests, for this issue. I sent a review request to @kylestetz just to get a pass-over, but it's probably not necessary. @rexxnar If you have time and are willing to pull that branch, then I could also fast-track it into master that way as well.

**Comment by mikegioia** [comment] 2019-05-27 13:48
This is now finally after so long merged into master and deployed as version 1.4.8. Sorry for the incredible delay here.

**Closed by mikegioia** 2019-05-27 13:48 UTC
Labels: bug
